apiVersion: apps/v1
kind: Deployment
metadata:
  name: earth-client
  labels:
    app: earth-client
spec:
  selector:
    matchLabels:
      app: earth-client
  template:
    metadata:
      labels:
        app: earth-client
    spec:
      containers:
        - name: earth-client
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_f32f252ed266
