apiVersion: v1
kind: Service
metadata:
  labels:
    app: earth-client
  name: earth-client
spec:
  ports:
    - name: 5173-5173
      port: 5173
      protocol: TCP
      targetPort: 5173
  selector:
    app: earth-client
  type: LoadBalancer
